"""Add favorite system tables - fixed

Revision ID: d0e6c75f904f
Revises: be81af13597f
Create Date: 2025-07-28 22:39:28.279932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0e6c75f904f'
down_revision = 'be81af13597f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('designs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('room_type', sa.String(length=100), nullable=False),
    sa.Column('design_style', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('product_suggestion', sa.Text(), nullable=True),
    sa.Column('products', sa.JSON(), nullable=True),
    sa.Column('gemini_response', sa.JSON(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('mood_board_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_designs_id'), 'designs', ['id'], unique=False)
    op.create_table('mood_boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('design_id', sa.String(length=36), nullable=True),
    sa.Column('mood_board_id', sa.String(length=100), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('prompt_used', sa.Text(), nullable=False),
    sa.Column('generation_time_seconds', sa.Integer(), nullable=True),
    sa.Column('image_size', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mood_boards_id'), 'mood_boards', ['id'], unique=False)
    op.create_index(op.f('ix_mood_boards_mood_board_id'), 'mood_boards', ['mood_board_id'], unique=True)
    op.create_table('user_favorite_designs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('design_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_favorite_designs_id'), 'user_favorite_designs', ['id'], unique=False)
    op.create_table('user_favorite_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('product_link', sa.String(length=500), nullable=True),
    sa.Column('product_category', sa.String(length=100), nullable=True),
    sa.Column('design_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_favorite_products_id'), 'user_favorite_products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_favorite_products_id'), table_name='user_favorite_products')
    op.drop_table('user_favorite_products')
    op.drop_index(op.f('ix_user_favorite_designs_id'), table_name='user_favorite_designs')
    op.drop_table('user_favorite_designs')
    op.drop_index(op.f('ix_mood_boards_mood_board_id'), table_name='mood_boards')
    op.drop_index(op.f('ix_mood_boards_id'), table_name='mood_boards')
    op.drop_table('mood_boards')
    op.drop_index(op.f('ix_designs_id'), table_name='designs')
    op.drop_table('designs')
    # ### end Alembic commands ###
