"""add_hashtag_system_tables

Revision ID: 756a96d20f06
Revises: d0e6c75f904f
Create Date: 2025-07-29 23:06:04.656241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '756a96d20f06'
down_revision = 'd0e6c75f904f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hashtags_id'), 'hashtags', ['id'], unique=False)
    op.create_index(op.f('ix_hashtags_name'), 'hashtags', ['name'], unique=True)
    op.create_table('design_hashtags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('design_id', sa.String(length=36), nullable=False),
    sa.Column('hashtag_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_design_hashtag', 'design_hashtags', ['design_id', 'hashtag_id'], unique=False)
    op.create_index('idx_design_order', 'design_hashtags', ['design_id', 'order_index'], unique=False)
    op.create_index(op.f('ix_design_hashtags_id'), 'design_hashtags', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_design_hashtags_id'), table_name='design_hashtags')
    op.drop_index('idx_design_order', table_name='design_hashtags')
    op.drop_index('idx_design_hashtag', table_name='design_hashtags')
    op.drop_table('design_hashtags')
    op.drop_index(op.f('ix_hashtags_name'), table_name='hashtags')
    op.drop_index(op.f('ix_hashtags_id'), table_name='hashtags')
    op.drop_table('hashtags')
    # ### end Alembic commands ###
