"""Add design system models

Revision ID: 81f4579f2df0
Revises: 3e61b324f5b0
Create Date: 2025-07-28 20:49:29.933195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81f4579f2df0'
down_revision = '3e61b324f5b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
