"""Add favorite system tables

Revision ID: be81af13597f
Revises: 81f4579f2df0
Create Date: 2025-07-28 22:38:41.361446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be81af13597f'
down_revision = '81f4579f2df0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
